---

name:
    mx-state-codes
version:
    0.1.0.0
github:
    "prikhi/mx-state-codes"
license:
    BSD3
license-file:
    LICENSE
author:
    "Pavan Rikhi"
maintainer:
    "pavan.rikhi@gmail.com"
copyright:
    "2019, Pavan Rikhi"
category:
    Data

extra-source-files:
    - README.md
    - CHANGELOG.md

synopsis:
    ISO 3166-2:MX Province Codes and Names

description: >
    This package contains a @Code@ data type containing each Mexican State, as
    well as functions for converting from and to the English subdivision names.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

dependencies:
    - base >= 4.7 && < 5
    - aeson >= 1 && < 2
    - text >= 1 && < 2

library:
    source-dirs:
        src

tests:
    mx-state-codes-test:
        main:
            Spec.hs
        source-dirs:
            test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - mx-state-codes
            - hspec
            - QuickCheck
